/*
 * md-book theme playground — controller.
 *
 * Renders a control panel bound to the `--md-book-*` token contract, applies the
 * edits live to a real <md-book> site running in the preview <iframe>, and emits
 * a ready-to-use theme stylesheet.
 *
 * No framework, no build step: this file is loaded as a native ES module.
 */
import {
  FIELDS,
  GROUPS,
  PRESETS,
  TOKEN_PREFIX,
  defaultState,
  fontKeyForValue,
  fontValueForKey,
  shadowKeyForValue,
  shadowValueForKey,
} from './tokens.js';

const STORAGE_KEY = 'md-book-playground:v1';

/** @typedef {{ shared: Record<string,string>, light: Record<string,string>, dark: Record<string,string> }} State */

const els = {
  controls: document.getElementById('pg-controls'),
  frame: /** @type {HTMLIFrameElement} */ (document.getElementById('pg-frame')),
  modeLight: document.getElementById('pg-mode-light'),
  modeDark: document.getElementById('pg-mode-dark'),
  preset: /** @type {HTMLSelectElement} */ (document.getElementById('pg-preset')),
  reset: document.getElementById('pg-reset'),
  css: /** @type {HTMLTextAreaElement} */ (document.getElementById('pg-css')),
  copy: document.getElementById('pg-copy'),
  download: document.getElementById('pg-download'),
  onlyChanged: /** @type {HTMLInputElement} */ (document.getElementById('pg-only-changed')),
  withMedia: /** @type {HTMLInputElement} */ (document.getElementById('pg-with-media')),
  showAdvanced: /** @type {HTMLInputElement} */ (document.getElementById('pg-advanced')),
  route: /** @type {HTMLSelectElement} */ (document.getElementById('pg-route')),
};

/** @type {State} */
let state = load() ?? defaultState();
/** @type {'light' | 'dark'} */
let mode = 'light';
let frameReady = false;

/* ---------------------------------------------------------------- persistence */

function load() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    const base = defaultState();
    return {
      shared: { ...base.shared, ...(parsed.shared ?? {}) },
      light: { ...base.light, ...(parsed.light ?? {}) },
      dark: { ...base.dark, ...(parsed.dark ?? {}) },
    };
  } catch {
    return null;
  }
}

function save() {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    /* private mode — non-fatal */
  }
}

/* --------------------------------------------------------------- state access */

/** Bucket a field's value lives in for the active mode. */
function bucketFor(field) {
  return field.scope === 'shared' ? state.shared : state[mode];
}

function getValue(field) {
  return bucketFor(field)[field.token] ?? '';
}

function setValue(field, value) {
  bucketFor(field)[field.token] = value;
  save();
  apply();
  syncExport();
}

/* -------------------------------------------------------------- CSS synthesis */

/** Format a stored value into its CSS form (adds units for ranges). */
function cssValue(field, raw) {
  if (raw === '' || raw == null) return null;
  if (field.type === 'range') return `${raw}${field.unit ?? ''}`;
  return String(raw);
}

function isChanged(field, raw) {
  const base = field.scope === 'shared' ? field.light : mode === 'dark' ? field.dark ?? field.light : field.light;
  return String(raw) !== String(base ?? '');
}

/**
 * Build the theme stylesheet.
 * @param {{ onlyChanged: boolean, withMedia: boolean }} opts
 */
function buildCss({ onlyChanged, withMedia }) {
  const rootLines = [];
  const darkLines = [];

  for (const field of FIELDS) {
    if (field.scope === 'shared') {
      const raw = state.shared[field.token];
      if (onlyChanged && String(raw) === String(field.light)) continue;
      const v = cssValue(field, raw);
      if (v != null) rootLines.push(`  ${TOKEN_PREFIX}${field.token}: ${v};`);
    } else {
      const rawL = state.light[field.token];
      const rawD = state.dark[field.token];
      if (!onlyChanged || String(rawL) !== String(field.light)) {
        const v = cssValue(field, rawL);
        if (v != null) rootLines.push(`  ${TOKEN_PREFIX}${field.token}: ${v};`);
      }
      const baseD = field.dark ?? field.light;
      if (!onlyChanged || String(rawD) !== String(baseD)) {
        const v = cssValue(field, rawD);
        if (v != null) darkLines.push(`  ${TOKEN_PREFIX}${field.token}: ${v};`);
      }
    }
  }

  const blocks = [];
  blocks.push('/* Generated by the md-book theme playground.');
  blocks.push(' * Load this AFTER md-book\'s style.css so it wins unlayered:');
  blocks.push(' *   <link rel="stylesheet" href="md-book/style.css">');
  blocks.push(' *   <link rel="stylesheet" href="this-file.css">');
  blocks.push(' */');
  blocks.push('');
  if (rootLines.length) blocks.push(`:root {\n${rootLines.join('\n')}\n}`);
  if (darkLines.length) {
    blocks.push(`\n:root[data-theme="dark"] {\n${darkLines.join('\n')}\n}`);
    if (withMedia) {
      blocks.push(
        `\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${darkLines
          .map((l) => `  ${l}`)
          .join('\n')}\n  }\n}`,
      );
    }
  }
  if (!rootLines.length && !darkLines.length) blocks.push('/* No changes yet — tweak a control. */');
  return `${blocks.join('\n')}\n`;
}

/* --------------------------------------------------------------- live preview */

function apply() {
  if (!frameReady) return;
  const win = els.frame.contentWindow;
  if (!win) return;
  // Hand the preview a full (unlayered) stylesheet plus the mode to force, so it
  // owns its own <style> and data-theme and nothing races the md-book runtime.
  win.postMessage(
    { type: 'pg-apply', css: buildCss({ onlyChanged: false, withMedia: true }), mode },
    window.location.origin,
  );
}

function syncExport() {
  els.css.value = buildCss({
    onlyChanged: els.onlyChanged.checked,
    withMedia: els.withMedia.checked,
  });
}

/* ------------------------------------------------------------------- controls */

function control(field) {
  const wrap = document.createElement('label');
  wrap.className = 'pg-field';
  wrap.dataset.token = field.token;

  const name = document.createElement('span');
  name.className = 'pg-field-label';
  name.textContent = field.label;
  const code = document.createElement('code');
  code.textContent = `${TOKEN_PREFIX}${field.token}`;
  name.appendChild(code);
  wrap.appendChild(name);

  const row = document.createElement('div');
  row.className = 'pg-field-row';
  wrap.appendChild(row);

  const value = getValue(field);

  if (field.type === 'color') {
    const picker = document.createElement('input');
    picker.type = 'color';
    picker.value = normaliseHex(value) || '#000000';
    const text = document.createElement('input');
    text.type = 'text';
    text.className = 'pg-hex';
    text.placeholder = field.optional ? '(derived)' : '#rrggbb';
    text.value = value;
    picker.addEventListener('input', () => {
      text.value = picker.value;
      setValue(field, picker.value);
    });
    text.addEventListener('change', () => {
      const v = text.value.trim();
      if (normaliseHex(v)) picker.value = normaliseHex(v);
      setValue(field, v);
    });
    row.append(picker, text);
    if (field.optional) {
      const clear = mkClear(() => {
        text.value = '';
        setValue(field, '');
      });
      row.appendChild(clear);
    }
  } else if (field.type === 'range') {
    const slider = document.createElement('input');
    slider.type = 'range';
    slider.min = String(field.min);
    slider.max = String(field.max);
    slider.step = String(field.step);
    slider.value = String(value || field.light);
    const num = document.createElement('output');
    num.className = 'pg-num';
    num.textContent = fmtNum(slider.value, field.unit);
    slider.addEventListener('input', () => {
      num.textContent = fmtNum(slider.value, field.unit);
      setValue(field, slider.value);
    });
    row.append(slider, num);
  } else if (field.type === 'font' || field.type === 'shadow') {
    const select = document.createElement('select');
    for (const [key, label] of field.options) {
      const opt = document.createElement('option');
      opt.value = key;
      opt.textContent = label;
      select.appendChild(opt);
    }
    const custom = document.createElement('option');
    custom.value = 'custom';
    custom.textContent = 'Custom…';
    select.appendChild(custom);

    const text = document.createElement('input');
    text.type = 'text';
    text.className = 'pg-custom';
    text.hidden = true;

    const keyFor = field.type === 'font' ? fontKeyForValue : (v) => shadowKeyForValue(v, mode);
    const valFor = field.type === 'font' ? fontValueForKey : (k) => shadowValueForKey(k, mode);

    const initialKey = keyFor(value);
    select.value = initialKey;
    if (initialKey === 'custom') {
      text.hidden = false;
      text.value = value;
    }
    select.addEventListener('change', () => {
      if (select.value === 'custom') {
        text.hidden = false;
        text.value = getValue(field);
        text.focus();
      } else {
        text.hidden = true;
        setValue(field, valFor(select.value));
      }
    });
    text.addEventListener('change', () => setValue(field, text.value.trim()));
    row.append(select);
    wrap.appendChild(text);
  }

  return wrap;
}

function mkClear(onClick) {
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'pg-clear';
  btn.textContent = '×';
  btn.title = 'Clear (use derived value)';
  btn.addEventListener('click', onClick);
  return btn;
}

function renderControls() {
  els.controls.replaceChildren();
  for (const group of GROUPS) {
    if (group.advanced && !els.showAdvanced.checked) continue;
    const section = document.createElement('section');
    section.className = 'pg-group';

    const details = document.createElement('details');
    details.open = !group.advanced;
    const summary = document.createElement('summary');
    summary.textContent = group.label;
    if (group.scope === 'mode') {
      const badge = document.createElement('span');
      badge.className = 'pg-badge';
      badge.textContent = mode;
      summary.appendChild(badge);
    }
    details.appendChild(summary);

    if (group.note) {
      const note = document.createElement('p');
      note.className = 'pg-note';
      note.textContent = group.note;
      details.appendChild(note);
    }
    for (const field of group.fields) {
      details.appendChild(control({ ...field, scope: group.scope, group: group.id }));
    }
    section.appendChild(details);
    els.controls.appendChild(section);
  }
}

/* ---------------------------------------------------------------------- utils */

function normaliseHex(v) {
  if (typeof v !== 'string') return '';
  const s = v.trim();
  if (/^#[0-9a-fA-F]{6}$/.test(s)) return s.toLowerCase();
  if (/^#[0-9a-fA-F]{3}$/.test(s)) {
    return `#${s[1]}${s[1]}${s[2]}${s[2]}${s[3]}${s[3]}`.toLowerCase();
  }
  return '';
}

function fmtNum(v, unit) {
  const n = Number(v);
  const s = Number.isInteger(n) ? String(n) : n.toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
  return unit ? `${s}${unit}` : s;
}

/* ------------------------------------------------------------------- wire-up */

function setMode(next) {
  mode = next;
  els.modeLight.classList.toggle('is-active', mode === 'light');
  els.modeDark.classList.toggle('is-active', mode === 'dark');
  els.modeLight.setAttribute('aria-pressed', String(mode === 'light'));
  els.modeDark.setAttribute('aria-pressed', String(mode === 'dark'));
  renderControls();
  apply();
  syncExport();
}

function applyPreset(key) {
  const preset = PRESETS[key];
  if (!preset) return;
  const next = defaultState();
  const patch = preset.patch();
  Object.assign(next.shared, patch.shared ?? {});
  Object.assign(next.light, patch.light ?? {});
  Object.assign(next.dark, patch.dark ?? {});
  state = next;
  save();
  renderControls();
  apply();
  syncExport();
}

els.modeLight.addEventListener('click', () => setMode('light'));
els.modeDark.addEventListener('click', () => setMode('dark'));

els.preset.addEventListener('change', () => {
  applyPreset(els.preset.value);
  els.preset.value = '';
});

els.reset.addEventListener('click', () => {
  state = defaultState();
  save();
  renderControls();
  apply();
  syncExport();
});

els.showAdvanced.addEventListener('change', renderControls);
els.onlyChanged.addEventListener('change', syncExport);
els.withMedia.addEventListener('change', syncExport);

els.copy.addEventListener('click', async () => {
  try {
    await navigator.clipboard.writeText(els.css.value);
    flash(els.copy, 'Copied');
  } catch {
    els.css.select();
    flash(els.copy, 'Select + ⌘C');
  }
});

els.download.addEventListener('click', () => {
  const blob = new Blob([els.css.value], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'md-book-theme.css';
  a.click();
  URL.revokeObjectURL(url);
});

els.route.addEventListener('change', () => {
  els.frame.src = `./preview.html#${els.route.value}`;
});

function flash(btn, text) {
  const original = btn.textContent;
  btn.textContent = text;
  btn.disabled = true;
  setTimeout(() => {
    btn.textContent = original;
    btn.disabled = false;
  }, 1200);
}

window.addEventListener('message', (event) => {
  if (event.origin !== window.location.origin) return;
  if (event.data?.type === 'pg-ready') {
    frameReady = true;
    apply();
  }
});
els.frame.addEventListener('load', () => {
  // Fallback in case the ready ping was missed (e.g. cached frame).
  frameReady = true;
  apply();
});

renderControls();
setMode('light');
